import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import React from "react";
import CustomNavbar from "@/components/UI/navbar/CustomNavbar";
import ScrollToTop from "@/components/UI/scroll-to-top";
import AdmNavbar from "@/components/adm/adm-navbar";
import CustomFooter from "@/components/UI/footer/custom-footer";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "PCNCA",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {

    return (
        <html className={'h-screen bg-slate-50'} lang="en">
        <body className={`${inter.className} `}>
        <Providers>
            <AdmNavbar/>
            <CustomNavbar/>
            <div className="flex flex-col">
                {children}
            </div>
            <ScrollToTop/>
            <CustomFooter/>
        </Providers>
        </body>
        </html>
    );
}
