import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import React from "react";
import CustomNavbar from "@/components/UI/navbar/CustomNavbar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "PCNCA",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <body className={`${inter.className} h-screen`}>
        <Providers>
            <CustomNavbar/>
            <div className="w-auto h-auto flex flex-col">
                {children}
            </div>
        </Providers>
        </body>
        </html>
    );
}
