export const articles = [
    {
        "id": 109,
        "title": "Carne de frango ganha competitividade com alta nos preços",
        "subtitle": "Valorização mais suave torna a proteína avícola uma opção mais acessível",
        "content": "A carne de frango tem se destacado no mercado, ampliando sua competitividade em relação às carnes bovina e suína, que apresentam altas mais acentuadas. Essa valorização mais suave torna a proteína avícola uma opção mais acessível para os consumidores no início de setembro.\n\n\n\nSegundo dados informados pelo Cepea, a menor valorização da carne de frango, em comparação com as concorrentes, está relacionada ao aumento do poder de compra da população e à maior demanda. Enquanto a oferta restrita impulsiona os preços das carnes suína e bovina, o setor avícola responde ao incremento da procura, com o atacado reforçando estoques para atender à demanda aquecida.",
        "publishedAt": "2024-09-19 23:59:14.577",
        "authorId": 3,
        "categoryId": 13,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/5ae27991230742b1a435da57bf753ae5_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado"
    },
    {
        "id": 107,
        "title": "Benefícios cosméticos dos ovos",
        "subtitle": "A clara de ovo tem propriedades que ajudam a clarear manchas escuras na pele",
        "content": "Os ovos, além de serem amplamente utilizados na culinária, têm ganhado reconhecimento por seus benefícios cosméticos. Sua composição rica em proteínas, vitaminas e ácidos graxos os torna aliados naturais em tratamentos para a pele e cabelos, promovendo resultados surpreendentes. Na rotina de beleza, os ovos podem ser utilizados de diversas maneiras, oferecendo soluções caseiras eficazes e acessíveis. Um exemplo é a máscara facial feita com clara de ovo, que ajuda a tonificar e firmar a pele. Combinada com iogurte, fonte de ácido láctico, essa mistura esfolia suavemente o rosto, deixando a pele macia e renovada, além de reduzir a aparência de poros dilatados.\n\n\n\nA gema do ovo, por sua vez, é uma excelente aliada para os cabelos, especialmente os danificados. Rica em ácidos graxos e vitaminas, a gema restaura a hidratação e o brilho dos fios, transformando cabelos secos e sem vida em madeixas mais saudáveis e luminosas. Para quem sofre com oleosidade no couro cabeludo, a clara do ovo pode ser aplicada como um tratamento eficaz, controlando a produção de óleo e deixando os cabelos mais leves e com aspecto limpo por mais tempo. A clara de ovo também pode ser utilizada em um esfoliante facial, combinado com açúcar, para remover células mortas e revitalizar a pele, promovendo uma aparência renovada e fresca.\n\nAlém disso, a clara de ovo tem propriedades que ajudam a clarear manchas escuras na pele e uniformizar o tom, deixando-a mais radiante e luminosa. Aplicar a clara sob os olhos também pode ajudar a reduzir olheiras e inchaços, proporcionando uma aparência descansada. No cuidado com as unhas, a gema do ovo é ideal para ser utilizada como um condicionador para cutículas, hidratando e fortalecendo-as, o que promove unhas mais saudáveis e evita a quebra. Uma máscara capilar feita com ovos, azeite e mel pode proporcionar hidratação profunda aos cabelos, aumentando o brilho e a resistência dos fios.\n\n\n\nOutro benefício interessante da clara de ovo é sua propriedade antimicrobiana, devido à presença da enzima lisozima. Essa enzima ajuda a reduzir o tamanho dos poros da pele, prevenindo o acúmulo de sujeira e poeira, o que pode contribuir para a redução da acne. Além disso, a clara de ovo possui propriedades anti-inflamatórias, tornando-se uma opção eficaz para acalmar a pele irritada. Incorporar os ovos na rotina de cuidados pessoais, seja na pele ou nos cabelos, pode ser uma maneira natural e econômica de obter uma aparência mais saudável e radiante.",
        "publishedAt": "2024-09-18 23:37:42.122",
        "authorId": 3,
        "categoryId": 13,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/33f430c0c10c470f9b69f05d25388dc2_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Saúde"
    },
    {
        "id": 110,
        "title": "Frangos tipo resfriado é opção prática para refeição de brasileiros",
        "subtitle": "O frango é o alimento de origem animal mais consumido no Brasil",
        "content": "O frango é o alimento de origem animal mais consumido no Brasil. Seu elevado valor nutricional, com baixo teor de gordura e alto nível de vitaminas, leva a população a consumi-lo cada vez mais. \"Saboroso, versátil e extremamente nutritivo, o frango pode ser servido de diversas formas e faz parte de múltiplas composições culinárias, o que amplia ainda mais sua importância gastronômica em nossas vidas\", comenta Mariana Nagata, diretora de marketing da Korin Alimentos. \n\n\n\nO consumo per capita de carne de frangos no Estado de São Paulo é de cerca de 45 quilos anuais. A produção supera 14,8 milhões de toneladas por ano em todo o Brasil. Além disso, as exportações atingiram 5,14 milhões de toneladas, em 2023. Com esses números, o Brasil é líder em exportação e um dos maiores produtores de frangos do mundo, de acordo com a Associação Brasileira de Proteína Animal (ABPA). \n\nA Korin Alimentos participa desse mercado em expansão. A empresa oferece o Frango tipo Resfriado Korin Boa Pedida - fresco e ideal para preparo rápido. Único no mercado na categoria sustentável, um importante diferencial do produto da Korin é oferecer mais praticidade na hora do preparo, já que não é necessário aguardar o processo de descongelamento para o início do cozimento. Basta retirar da embalagem e preparar. Além disso, está sempre fresco nos supermercados à disposição dos consumidores. \n\n\n\n\"As pessoas ajustam seus hábitos alimentares em busca de praticidade. Dessa forma, optam por alimentos mais fáceis de preparar e de rápido cozimento\", ressalta a diretora de marketing. \"O frango é o prato ideal para quem não tem muito tempo a perder e quer qualidade\". \n\nCom presença majoritária nos mercados de São Paulo e Rio de Janeiro, os Frangos Resfriados Korin Boa Pedida têm rastreabilidade e preocupação com o bem-estar animal. A criação não recebe antibióticos nem anticoccidianos. \"Esse sistema faz parte do princípio da Agricultura Natural, preconizado pelo pensador japonês Mokiti Okada (1882-1955), que tem como objetivo resgatar a pureza do solo e dos alimentos e preservar a diversidade e o equilíbrio biológico, contribuindo para a elevação da qualidade da vida humana\", informa Mariana. \n\n\n\nOs Frangos Resfriados Korin Boa Pedida são oferecidos nas versões com bandejas de 600 gramas e inteiro. Os cortes disponíveis são: coração, coxa com sobrecoxa sem osso, coxa, coxinha da asa, fígado, filé de coxa com sobrecoxa sem pele, filé de peito, filé sassami, meio da asa, moela, sobrecoxa, sobrecoxa sem pele, sobrecoxa sem osso e frango inteiro.",
        "publishedAt": "2024-09-18 23:41:32.881",
        "authorId": 3,
        "categoryId": 13,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/ffb6701390b3421aa1be8c8368a8b425_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Gastronomia"
    },
    {
        "id": 86,
        "title": "EUA: 65% da safra de milho está em boas a excelentes condições",
        "subtitle": "Safra de milho alcança 9% dos EUA",
        "content": "O relatório do Weekly Weather and Crop Bulletin, publicado pelo Departamento de Comércio dos EUA em parceria com a Administração Oceânica e Atmosférica Nacional (NOAA) e o Departamento de Agricultura (USDA) apontou que 85% da área de milho nos Estados Unidos já estava amassada até 15 de setembro. Esse índice está 3 pontos percentuais abaixo do registrado no ano passado, mas 1 ponto à frente da média dos últimos cinco anos. Quanto à maturidade da safra, 45% da área de milho do país já alcançou esse estágio, um número que é 3 pontos percentuais inferior ao de 2023, mas 7 pontos à frente da média.\n\n\n\nEm relação à colheita, 9% da área plantada foi colhida até o fim da semana, o que representa 1 ponto percentual à frente do mesmo período do ano passado e 3 pontos à frente da média histórica. A colheita está em andamento em 15 dos 18 estados produtores estimados.\n\n\n\nAlém disso, 65% da área de milho do país foi classificada como estando em condições de boas a excelentes, uma melhora de 1 ponto percentual em comparação à semana anterior e 14 pontos acima do registrado no ano passado. No estado de Iowa, maior produtor de milho do país, 77% da safra foi classificada nessas condições favoráveis.",
        "publishedAt": "2024-09-18 22:52:01.439",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/7b0572e203584a089ebeb0c2b772fc65_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mundo"
    },
    {
        "id": 88,
        "title": "Custo de produção do milho supera preço do cereal, aponta Imea",
        "subtitle": "Ciclo futuro do milho em Mato Grosso continua sendo um desafio",
        "content": "Segundo dados do Instituto Mato-grossense de Economia Agropecuária (Imea), o ponto de equilíbrio dos indicadores de custo de produção para a próxima temporada de milho em Mato Grosso revela um cenário desafiador para os produtores. Os custos de produção para o custeio, COE (Custo Operacional Efetivo), COT (Custo Operacional Total) e CT (Custo Total) foram estimados em R$ 28,96/sc, R$ 41,17/sc, R$ 45,99/sc e R$ 54,38/sc, respectivamente. Esses valores indicam que o preço do milho no estado Cobre apenas as despesas relacionadas ao custeio da temporada.\n\n\n\nOs cálculos de ponto de equilíbrio (P.E) utilizaram dados do custo de produção do projeto Acapa-MT, divulgados em setembro de 2024, e a produtividade média das últimas três safras. Com isso, o ciclo futuro do milho em Mato Grosso continua sendo um desafio, exigindo que os produtores mantenham uma gestão rigorosa dos custos, aproveitem as oportunidades de valorização do cereal e otimizem as relações de troca com os insumos.\n\n\n\nAlém disso, a produtividade permanece como um fator fundamental e indefinido que pode impactar a rentabilidade, desempenhando um papel fundamental na definição das margens dos produtores.",
        "publishedAt": "2024-09-18 22:58:45.317",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/4f78c51a69ea40879b7eadfba5c7a3eb_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Produção"
    },
    {
        "id": 106,
        "title": "Potencial da carne bovina no México",
        "subtitle": "A Abiec apresentou dados sobre a evolução dos embarques",
        "content": "A Associação Brasileira das Indústrias Exportadoras de Carne (Abiec) divulgou uma nota informando sua participação em um evento realizado na Embaixada do Brasil no México, na quinta-feira (29). A iniciativa, organizada em parceria com a Associação Brasileira de Proteína Animal (ABPA), fez parte de uma missão oficial promovida pelo Ministério da Agricultura e Pecuária (Mapa) ao país. O México, um dos mercados mais recentes abertos à carne bovina brasileira, tem registrado um crescimento expressivo nas exportações, fato destacado pela Abiec durante o encontro.\n\n\n\nSegundo a nota, a Abiec apresentou dados sobre a evolução dos embarques de carne bovina para o México, que tiveram um salto significativo entre janeiro e julho de 2024, comparado ao mesmo período de 2023. O volume exportado passou de 288 toneladas em 2023 para impressionantes 23.108 toneladas em 2024. A diretora de Relações Internacionais da Abiec, Lhais Sparvoli, atribuiu esse crescimento à alta demanda do mercado mexicano por carne de qualidade e ao reconhecimento dos rigorosos padrões de segurança e sanidade da carne brasileira.\n\n\n\nA associação também destacou o papel crucial da parceria com a ApexBrasil, através do projeto Brazilian Beef, no sucesso dessas exportações. Além de fortalecer o comércio bilateral, a Abiec ressaltou que as importações de carne bovina brasileira ajudam o México a otimizar seu mix de produtos exportados, permitindo ao país atender à demanda interna e ganhar escala para exportar outros cortes estratégicos. Na nota, Lhais Sparvoli conclui que eventos como esse são fundamentais para estreitar as relações bilaterais e fazem parte de uma agenda estratégica contínua, visando à consolidação e ao crescimento do mercado de carne bovina brasileira no México.",
        "publishedAt": "2024-09-18 23:50:38.587",
        "authorId": 3,
        "categoryId": 12,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/95ab384ea6a44cb69ae5ea6001e40917_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Internacional"
    },
    {
        "id": 111,
        "title": "Mercado de açúcar cai 2,4% na semana",
        "subtitle": "Outro fator que pressionou os preços foram os bons níveis de chuvas na Índia",
        "content": "Segundo informações da StoneX, o mercado de açúcar e etanol registrou quedas significativas na última semana, influenciado por fatores climáticos e econômicos. Os preços do açúcar bruto em Nova Iorque encerraram a semana com uma retração consolidada de 2,4%, situando-se em US¢ 18,03 por libra-peso. Essa queda foi reflexo da divulgação dos dados da safra do Centro-Sul na segunda metade de julho de 2024, além do aumento da aversão ao risco nos mercados financeiros globais.\n\n\n\nOutro fator que pressionou os preços do açúcar foram os bons níveis de chuvas na Índia durante a temporada de monções. Esses elementos contribuíram para uma tendência geral de baixa, apesar de uma alta pontual de 0,84% na sexta-feira (16). A combinação desses fatores adversos resultou em um movimento baixista consolidado no mercado.\n\nNo mercado de etanol, os dados do CEPEA revelam uma desvalorização de 1,4% no etanol hidratado (média São Paulo) entre os dias 08 e 16 de julho, com o preço ficando em R$ 2,5977 por litro, sem impostos. Essa queda foi influenciada pela desaceleração da demanda em função dos preços elevados. As usinas, ainda em pico de safra, ajustaram seus preços, como mostra o indicador da StoneX para o etanol base PVU Ribeirão Preto-SP, que registrou uma queda de 1,6%, retornando ao patamar de R$ 3,10 por litro.\n\n\n\nMesmo com a estabilidade dos preços entre R$ 3,05 e R$ 3,10 por litro desde o final de julho, as perspectivas para o etanol seguem otimistas, impulsionadas pela robusta demanda. As vendas das usinas do Centro-Sul em julho totalizaram 1,77 milhão de metros cúbicos no mercado interno, o maior volume desde 2019. A continuidade dessa demanda forte sugere que, apesar das recentes quedas, o mercado de etanol pode manter uma tendência altista no curto prazo.",
        "publishedAt": "2024-09-18 23:42:11.670",
        "authorId": 3,
        "categoryId": 7,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/372fb1c5170f4d328581722abc49303d_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado"
    },
    {
        "id": 87,
        "title": "Milho tem negócios pontuais",
        "subtitle": "No Paraná se viu um mercado com poucos lotes",
        "content": "No mercado do milho do estado do Rio Grande do Sul foram vistos negócios pontuais ao sul do estado, de acordo com informações divulgadas pela TF Agroeconômica. “Mercado lento. Nas indicações, manutenção: Santa Rosa a R$ 63,00; Não-Me-Toque a R$ 64,00; Marau e Gaurama R$ 64,50; Arroio do Meio, Lajeado e Frederico Westphalen a R$ 66,00 e Montenegro a R$ 67,00. Vendedores a partir de R$ 63,00 no FOB interior. Negócios pontuais em Panambi, onde 700 tons rodaram a R$ 64,00 no CIF indústria, entrega imediata”, comenta.\n\n\n\nSanta Catarina tem diferença entre R$ 2,00 a R$ 3,00 e vendedores com pouco prazo travam negócios. “Produtores com pedidas ao menos R$ 2,00 acima, em que compradores hoje indicam a partir de R$ 60,00 no interior e R$ 63,00/64,00 CIF fábricas. Rumores de negócios a R$ 64,00/64,50 no CIF oeste. Nas indicações, Chapecó a R$ 62,00; Campos Novos R$ 64,00; Rio do Sul a R$ 64,00; Videira R$ 63,00. Não ouvimos negócios nesta segunda-feira”, completa.\n\nNo Paraná se viu um mercado com poucos lotes. “Mercado com negócios pontuais reportados. No porto, indicações a R$ 63,00 set/64,00 nov/65,00 dez. No norte, indicações a R$ 58,00 (+1,00); Cascavel a R$ 57,00 (+1,00); Campos Gerais R$ 58,00 (-1,00); Guarapuava a R$ 58,00; Londrina R$ 57,50. Preços balcão no sudoeste a R$ 52,00; norte a R$ 54,00; oeste R$ 54,00 e centro-oeste R$ 55,00. Rumores de novos negócios na ferrovia Maringá, a R$ 62,00 outubro, onde teriam rodado pelo menos 5 mil toneladas”, indica.\n\n\n\nNo Mato Grosso do Sul, a maioria dos preços subiu. “Em Maracaju, indicações de R$ 53,00 (+1,00); Dourados a R$ 54,00 (+R$ 1,00); Naviraí R$ 54,00 (-R$ 1,00) e São Gabriel a R$ 49,00. Produtores iniciam ofertas FOB a R$ 52,00 com maior parte das pedidas concentradas em R$ 55,00, base interior. Não ouvimos sobre negócios nesta segunda-feira”, conclui.",
        "publishedAt": "2024-09-18 22:57:46.511",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/f0b749daba5a4fc1a60b1842c376bbac_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Produtividade"
    },
    {
        "id": 89,
        "title": "China reduz importações de milho, afetando mercado brasileiro",
        "subtitle": "Plantio da safra de verão avança no Sul",
        "content": "A análise do Grão Direto indica que a produção de milho nos EUA teve um leve aumento, de 384,74 para 385,73 milhões de toneladas. No entanto, a produção mundial caiu de 1.219,82 para 1.218,57 bilhões de toneladas, afetando os estoques globais. O USDA informou que os EUA venderam 1,561 milhão de toneladas, superando as expectativas de 700 mil a 1,6 milhão de toneladas.\n\n\n\nSegundo a análise produzida pelo Grão Direto, o Departamento de Agricultura dos Estados Unidos (USDA) revisou para baixo suas projeções de importação de milho pela China, de 23 para 21 milhões de toneladas. Essa redução pode ser um indicativo de que o país asiático está se aproximando da autossuficiência na produção de milho, o que pode impactar diretamente a demanda pelo produto brasileiro.\n\nNo Brasil, os produtores têm mostrado resistência a novas vendas após a quitação de dívidas com vendas anteriores, pressionando os compradores a oferecer preços mais atrativos. No entanto, há ainda grande volume de milho para ser negociado, enquanto a colheita norte-americana avança, oferecendo concorrência no mercado internacional.\n\n\n\nO plantio da safra de verão segue em ritmo moderado nos estados do Sul, com o Rio Grande do Sul registrando 37% da área total plantada, abaixo dos 44% do ano anterior. O clima instável em outras regiões do Brasil, contudo, gera incertezas sobre o avanço do plantio do cereal.\n\nNas exportações, o USDA reduziu a projeção brasileira de 50 para 48 milhões de toneladas, em função da menor produção e do ritmo mais lento de exportações. Mesmo assim, o número ainda está acima da estimativa da Conab, de 36 milhões de toneladas, com o mercado prevendo um patamar entre 40 e 42 milhões de toneladas, cerca de 30% abaixo do previsto inicialmente. Esse cenário pode manter as cotações em alta pelo terceiro mês consecutivo.",
        "publishedAt": "2024-09-18 22:59:18.767",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/6b0d3abbd6884b828203b793a22aff0c_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mundo"
    },
    {
        "id": 90,
        "title": "Preços do milho sob pressão",
        "subtitle": "Esses movimentos indicam a necessidade de atenção",
        "content": "De acordo com a TF Agroeconômica, a recente resistência nos preços do milho na B3 acendeu um alerta para investidores e agricultores. Caso essa resistência seja superada na próxima semana, o ideal é manter a posição; caso contrário, pode ser o momento de sair das posições compradas. Embora os preços do milho tenham subido ao longo do mês, o relatório da Conab trouxe um impacto negativo no dia ao registrar aumento nos estoques finais, gerando pressão de queda nos preços.\n\n\n\nEntre os fatores de alta, destacam-se o atraso na colheita nos Estados Unidos, causado pelo furacão Francine, e o aumento das exportações brasileiras de milho. A ANEC revisou para cima suas projeções de embarques para setembro, o que elevou os prêmios de exportação no Brasil, impulsionados pela necessidade dos exportadores de cumprir compromissos. Além disso, o aumento da seca em regiões dos EUA, conforme relatório do USDA, segue afetando o mercado, com 18% da área agrícola americana sofrendo algum nível de seca.\n\n\n\nPor outro lado, os fatores de baixa incluem o aumento dos estoques finais de milho no Brasil, que passaram de 4,97 milhões para 5,05 milhões de toneladas, segundo a Conab, e a queda de 5,36% nos preços do suíno, um grande consumidor de milho. Além disso, a entrada da safra comercial brasileira no mercado de exportação exerce pressão adicional sobre os preços, mesmo com uma previsão de exportações menor do que no ciclo anterior. Esses movimentos indicam a necessidade de atenção ao comportamento do mercado, pois, apesar dos aumentos recentes, as flutuações de oferta e demanda podem impactar os preços de maneira significativa nos próximos dias.",
        "publishedAt": "2024-09-18 23:00:46.319",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/ad3fdec02f5c45d19ae948046fc567bd_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado"
    },
    {
        "id": 115,
        "title": "Milho fecha semana em alta na B3",
        "subtitle": "Na Bolsa de Chicago, o milho fechou dia e semana em alta",
        "content": "Na Bolsa de Mercadorias de São Paulo, o milho fechou a semana em alta, acompanhado do mercado norte-americano nesta sexta-feira, de acordo com informações divulgadas pela TF Agroeconômica. “Os contratos futuros de grãos registraram alta acompanhado o mercado americano. Apesar dos relatórios de oferta e demanda do USDA e da Conab apresentarem dados baixistas, os dois mercados seguraram as cotações. Na Bolsa de Chicago, o vencimento setembro/24 fechou cotado a US$ 3,94, em uma valorização de 7,75 pontos”, comenta.\n\n\n\n“Diante deste quadro, as cotações futuras fecharam variações em alta no dia: o vencimento de setembro/24 foi de R$ 63,91 apresentando alta de R$ 0,13 no dia, alta de R$ 1,09 na semana; novembro/24 fechou a R$ 67,82, alta de R$ 1,21 no dia, alta de R$ 1,70 na semana; o vencimento janeiro/25 fechou a R$ 70,60, alta de R$ 0,90 no dia e alta de R$ 1,31 na semana”, completa.\n\nNa Bolsa de Chicago, o milho fechou dia e semana em alta com fundos recomprando posições. “A cotação de dezembro24, referência para a nossa safra de inverno, fechou em alta de 1,79 % ou $ 7,25 cents/bushel a $ 413,25. A cotação para março25, fechou em alta de 1,53 % ou $ 6,50 cents/bushel a $ 431,00”, indica.\n\n\n\n“O mercado voltou a cobrir posições em aberto do milho, movimento que transbordou do trigo para o cereal. A melhora da paridade para o Dólar em relação ao Real também deu suporte para milho. Segundo o USDA o México e a Europa devem aumentar as suas importações de milho. Ao longo da semana, as condições secas no Brasil, no começo do plantio do milho de primeira safra deram suporte aos preços. Com isso o milho fechou o acumulado da semana em alta de 1,72% ou $7,00 cents/bushel”, conclui.",
        "publishedAt": "2024-09-18 22:47:13.310",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/efe634a1e2564f26a6bf53f00d828b5b_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Produção"
    },
    {
        "id": 91,
        "title": "Milho lento no Sul",
        "subtitle": "O mercado do Paraná, enquanto isso, segue sem negócios",
        "content": "No mercado de milho do estado do Rio Grande do Sul o mercado ainda está lento, segundo informações divulgadas pela TF Agroeconômica. “Mercado lento. Nas indicações, manutenção: Santa Rosa a R$ 63,00; Não-Me-Toque a R$ 64,00; Marau e Gaurama R$ 64,50; Arroio do Meio, Lajeado e Frederico Westphalen a R$ 66,00 e Montenegro a R$ 67,00. Vendedores a partir de R$ 63,00 no FOB interior. Não ouvimos negócios nesta quinta-feira”, comenta.\n\n\n\nEm Santa Catarina as indicações foram mantidas. “Produtores com pedidas ao menos R$ 2,00 acima, em que compradores hoje indicam a partir de R$ 60,00 no interior e R$ 63,00/64,00 CIF fábricas. Rumores de negócios a R$ 64,00/64,50 no CIF oeste. Nas indicações, Chapecó a R$ 62,00; Campos Novos R$ 64,00; Rio do Sul a R$ 64,00; Videira R$ 63,00. Em negócios ao oeste, viu-se milho sendo negociado entre R$ 63,00 até 64,00 CIF, a depender do vencimento, onde corretores relatam negócios em pelo menos 5 mil toneladas”, completa.\n\nO mercado do Paraná, enquanto isso, segue sem negócios. “Mercado com negócios pontuais reportados. No porto, indicações a R$ 63,00 set/64,00 nov/65,00 dez. No norte, indicações a R$ 57,00 (+1,00); Cascavel a R$ 56,00 (+2,00); Campos Gerais R$ 59,00 (+1,00); Guarapuava a R$ 58,00; Londrina R$ 57,50. Preços balcão no sudoeste a R$ 52,00; norte a R$ 54,00; oeste R$ 54,00 e centro-oeste R$ 55,00. Rumores de novos negócios na ferrovia Maringá, a R$ 62,00 outubro”, indica.\n\n\n\nNo Mato Grosso do Sul os preços subiram. “Em Maracaju, indicações de R$ 53,00 (+1,00); Dourados a R$ 54,00 (+R$ 1,00); Naviraí R$ 54,00 (-R$ 1,00) e São Gabriel a R$ 49,00. Produtores iniciam ofertas FOB a R$ 52,00 com maior parte das pedidas concentradas em R$ 55,00, base interior. Negócios pontuais em Naviraí, onde uma indústria levou 2 mil tons entrega setembro/pgto final do mês a R$ 54,00”, conclui.",
        "publishedAt": "2024-09-18 23:01:42.130",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/44c7a8418c8843dd81abe850d4635a08_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado brasileiro"
    },
    {
        "id": 93,
        "title": "Estoques de café no Japão caem, mas demanda mantém projeção estável",
        "subtitle": "Demanda aparente no Japão sofreu reduções nos últimos anos",
        "content": "Segundo informações divulgadas pela Hedgepoint Global Markets, os estoques de café no Japão continuam em queda. De acordo com os dados mais recentes da Japan Coffee Association (JCA), houve uma redução de 3,3% entre maio e julho, levando o volume para 2,42 milhões de sacas, um nível estável em relação ao ano passado, mas ainda abaixo da média histórica de 2,8 milhões de sacas. Essa diminuição é acompanhada por uma estabilização na demanda aparente para a temporada de 2023/24 (outubro de 2023 a junho de 2024), que já se aproxima dos níveis de 2022/23.\n\n\n\nLaleska Moda, analista de café da Hedgepoint, destaca que, apesar dos menores estoques oferecerem suporte para as cotações, a demanda aparente no Japão sofreu reduções nos últimos anos. No entanto, ela ressalta que o consumo está estabilizado, e a expectativa é que a demanda total da temporada 23/24 atinja 6,2 milhões de sacas, o que seria praticamente o mesmo volume de 2022/23.\n\n**Exportações brasileiras batem recorde**\n\nEnquanto o Japão lida com a queda dos estoques, o Brasil registra recordes nas exportações de café. Em agosto, o país exportou 3,73 milhões de sacas, um aumento de 0,7% em relação ao mesmo período do ano passado, segundo dados do Cecafé. Esse crescimento foi impulsionado principalmente pelo conilon, cujas exportações subiram 31,4% e atingiram um novo recorde histórico de 924,6 mil sacas.\n\n\n\nA participação do conilon no mercado internacional vem crescendo, especialmente devido à restrição de oferta em países como o Vietnã. \"O conilon brasileiro está ganhando força em destinos como a Europa, Japão e outros países asiáticos, e esperamos que essa tendência continue forte em 2024/25\", destaca a Hedgepoint.\n\n**Tendências** \n\nA participação do Brasil nas importações japonesas também aumentou, enquanto países como Vietnã e outros da América Latina perderam espaço. Segundo a Hedgepoint, a oferta limitada no Sudeste Asiático e os problemas climáticos têm impulsionado o café brasileiro, especialmente o conilon, que continua a ser uma escolha preferida por conta do seu preço competitivo.\n\n\n\nCom a oferta global de robusta restrita, as exportações brasileiras devem permanecer em níveis elevados, consolidando o país como o principal fornecedor global de café, enquanto os outros produtores lidam com dificuldades de produção.",
        "publishedAt": "2024-09-18 23:50:08.947",
        "authorId": 3,
        "categoryId": 6,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/697d512ae68a48f3b4330d4177f5cf6e_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Internacional"
    },
    {
        "id": 113,
        "title": "EUA: milho registra crescimento de produção",
        "subtitle": "EUA: milho registra crescimento apesar de área colhida reduzida",
        "content": "De acordo com a análise semanal do Instituto Mato-grossense de Economia Agropecuária (Imea), segundo dados divulgados pelo Departamento de Agricultura dos Estados Unidos (USDA) em setembro de 2024, a área colhida para a safra 2024/25 de [milho](https://www.agrolink.com.br/culturas/milho?utm_source=agrolink-detalhe-noticia\\&utm_medium=detalhe-noticia\\&utm_campaign=links-internos) manteve-se em 33,47 milhões de hectares, uma queda de 4,4% em relação à temporada anterior.\n\n\n\nNo entanto, a produção apresentou um leve aumento de 0,26% em comparação ao relatório de agosto, totalizando 385,73 milhões de toneladas.\n\nEsse crescimento na produção reflete o bom desempenho das lavouras, com 65% delas classificadas como em condições boas ou excelentes, 9 pontos percentuais acima da média das últimas cinco safras no mesmo período. A colheita começou na semana anterior e, até o dia 15 de setembro, alcançou 9% da área total estimada, o que representa um avanço de 3 pontos percentuais em relação à média histórica.",
        "publishedAt": "2024-09-18 23:39:51.382",
        "authorId": 3,
        "categoryId": 2,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/df4cec1fdf0a44c3b6cc78fba2aceb13_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Internacional"
    },
    {
        "id": 112,
        "title": "Açúcar fecha em baixa nos mercados internacionais",
        "subtitle": "Datagro reduz estimativa de produção",
        "content": "Os contratos futuros do açúcar fecharam a quarta-feira (4) em baixa nos mercados internacionais, com os comerciantes, segundo analistas ouvidos pela Reuters, destacando que “o mercado ficou tecnicamente fraco depois de não conseguir atingir novos picos de dois meses nesta semana. Na semana passada, ele se recuperou, impulsionado pelos incêndios nos canaviais do Brasil”.\n \n“No entanto, eles disseram que o açúcar continua sustentado pela situação de seca no Brasil e pela decisão da Índia de permitir que as usinas de açúcar usem o caldo de cana para produzir etanol”, destacou a Agência Internacional de Notícias.\n \nOntem a Consultoria Datagro reduziu para 39,3 milhões de toneladas a projeção de produção de açúcar no Centro-Sul do Brasil na atual temporada. A redução leva em conta os impactos das condições climáticas desfavoráveis atuais.\n \nNova York\n \nNa ICE Futures de Nova York, o açúcar bruto fechou contratado ontem, no lote outubro/24, a 19,24 centavos de dólar por libra-peso, baixa de 25 pontos, ou 1,3%, no comparativo com os preços da véspera. Já a tela março/25 caiu 25 pontos, contratada a 19,56 cts/lb. Os demais contratos recuaram entre 1 e 20 pontos, com a exceção do lote julho/26 que subiu 4 pontos.\n \nLondres\n \nJá o açúcar branco listado na ICE Futures Europe de Londres fechou no vermelho em todos os lotes. O vencimento outubro/24 foi contratado a US$ 539,10 a tonelada, recuo de 2,70 dólares no comparativo com os preços da véspera. A tela dezembro/24 caiu 3,30 dólares, contratada a US$ 528,80 a tonelada. Os demais lotes recuaram entre 2,40 e 4,20 dólares.\n \nMercado doméstico\n \nNo mercado interno a quarta-feira foi de alta nas cotações do açúcar cristal medidas pelo Indicador Cepea/Esalq, da USP. A saca de 50 quilos foi comercializada ontem a R$ 136,94 contra R$ 135,97 de terça-feira, valorização de 0,71% no comparativo.\n \nEtanol hidratado\n \nJá o etanol hidratado fechou pelo terceiro dia seguido em queda pelo Indicador Diário Paulínia. O biocombustível foi negociado ontem a R$ 2.607,00 o m³, contra R$ 2.631,00 o m³ praticado na véspera, desvalorização de 0,91% no comparativo entre os dias.",
        "publishedAt": "2024-09-18 23:43:31.900",
        "authorId": 3,
        "categoryId": 7,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/9a35558ae78843f09b0283d7edaf085a_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Importação"
    },
    {
        "id": 94,
        "title": "Qualidade da soja mantém-se elevada nos EUA",
        "subtitle": "64% das lavouras estão em boas condições",
        "content": "O mais recente relatório do Weekly Weather, divulgado pelo Departamento de Comércio dos EUA em parceria com a Administração Oceânica e Atmosférica Nacional (NOAA) e o Departamento de Agricultura (USDA), indicou que 44% da queda de folhas das lavouras de soja foi concluída até 15 de setembro. Esse número está 3 pontos percentuais atrás do registrado no ano passado, mas 7 pontos à frente da média de cinco anos.\n\n\n\nA colheita de soja alcançou 6% de sua área plantada até a mesma data, um avanço de 2 pontos percentuais em relação a 2023 e 3 pontos à frente da média de cinco anos. A colheita já estava em andamento em 17 dos 18 estados estimados.\n\nEm termos de qualidade, 64% das plantações de soja foram classificadas como boas a excelentes em 15 de setembro, um leve recuo de 1 ponto percentual em relação à semana anterior, mas ainda 12 pontos percentuais acima do índice registrado no mesmo período do ano passado.",
        "publishedAt": "2024-09-18 23:22:23.163",
        "authorId": 3,
        "categoryId": 3,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/5ea92573f29343e192d278c2d3300f4a_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Internacional"
    },
    {
        "id": 95,
        "title": "Oferta mundial de soja afeta mercado brasileiro",
        "subtitle": "Demanda cresce por óleo de soja",
        "content": "De acordo com dados da edição de setembro do boletim Agro em Dado da Secretaria de Estado de Agricultura, Pecuária e Abastecimento (Seapa), a oferta mundial recorde de soja na temporada 2023/24 e as projeções de alta disponibilidade para 2024/25, juntamente com variação negativa do dólar frente ao real em agosto, resultaram na desvalorização das cotações da soja tanto no mercado brasileiro quanto no internacional na primeira quinzena do mês.\n\n\n\nNo acumulado de exportações de janeiro a julho, o Brasil registrou um aumento de 3,0% no volume exportado de produtos do complexo soja em comparação ao mesmo período de 2023. No entanto, o valor arrecadado caiu 15,4%, refletindo a desvalorização da oleaginosa no mercado externo.\n\nO óleo de soja, por sua vez, teve valorização no mercado nacional em julho, impulsionado pela maior demanda de indústrias de biodiesel. Esse foi o mês com maior volume de embarques em 2024, totalizando 207,7 mil toneladas, um aumento de 48,9% em relação a junho, com receita de US$196,7 milhões.\n\n\n\nEm Goiás, terceiro maior exportador de óleo de soja do Brasil, foram embarcadas 106,8 mil toneladas entre janeiro e julho de 2024, somando US$97,7 milhões, representando quedas de 22,1% no volume e 32,2% no valor em relação ao mesmo período do ano anterior. Abril foi o mês de destaque, com 25,5 mil toneladas exportadas e faturamento de US$22,5 milhões, impulsionado pela valorização do dólar.\n\nO farelo de soja também teve impacto. De janeiro a julho, o Brasil exportou 13,3 milhões de toneladas, com um aumento de 3,6% em volume, mas uma queda de 14,3% no valor, totalizando US$5,7 bilhões. Goiás, quarto no ranking nacional, embarcou 1,5 milhão de toneladas, ao valor de US$668,9 milhões, recuando 15,8%.",
        "publishedAt": "2024-09-18 23:22:59.013",
        "authorId": 3,
        "categoryId": 3,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/59b6f442c49746cb8b0dcd39754853e9_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado"
    },
    {
        "id": 96,
        "title": "Falta de chuvas atra semeadura da soja em Mato Grosso",
        "subtitle": "No mesmo período do ano passado, 1,82% da área já havia sido cultivada no estado",
        "content": "Desde o dia 7 de setembro, os produtores de Mato Grosso estão autorizados a iniciar a semeadura da safra de soja 2024/25. No entanto, segundo dados do Instituto Mato-grossense de Economia Agropecuária (Imea), os trabalhos no campo têm ocorrido de forma pontual, restritos a áreas irrigadas por pivô central. A razão para o avanço limitado nessas regiões se deve ao baixo volume de água nos reservatórios.\n\n\n\nO Imea atribui esse cenário de seca à mudança nas temperaturas do Oceano Pacífico, que passou de um fenômeno El Niño para uma condição de neutralidade no início de 2024. Essa alteração climática tem retardado as primeiras chuvas em Mato Grosso, complicando o início do plantio.\n\n\n\nDe acordo com projeções do Instituto Nacional de Meteorologia (Inmet), o estado deve receber entre 1 e 3 mm de precipitação nos próximos sete dias, volume considerado insuficiente para a semeadura adequada. No mesmo período do ano passado, 1,82% da área já havia sido cultivada no estado, cenário que deve se repetir com atraso em 2024.\n\n\n\nCom a previsão de chuvas aquém do necessário, o setor agropecuário de Mato Grosso aguarda com apreensão a evolução climática nas próximas semanas para evitar impactos negativos na produtividade da safra.",
        "publishedAt": "2024-09-18 23:23:33.624",
        "authorId": 3,
        "categoryId": 3,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/e93429e3193e4c5a9d14e4f495000039_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado nacional"
    },
    {
        "id": 97,
        "title": "Mercado da soja “desanimado”",
        "subtitle": "Em Santa Catarina, os negócios continuam estagnados",
        "content": "O mercado da soja do estado do Rio Grande do Sul continuou desanimado devido à valorização do real frente ao dólar, o que resultou em poucos negócios reportados, segundo informações divulgadas pela TF Agroeconômica. Os preços de hoje para entrega em outubro e pagamento em 15/10 foram: R$ 139,00 no Porto. No interior, os valores seguiram conforme as praças: R$ 131,50 em Cruz Alta, R$ 132,00 em Passo Fundo, R$ 131,00 em Ijuí e R$ 130,50 em Santa Rosa/São Luiz (pagamento em 04/10).\n\n\n\nEm Santa Catarina, os negócios continuam estagnados. Segundo o Epagri, Santa Catarina deve colher cerca de 3 milhões de toneladas de soja, um aumento de 12,77% em relação à safra passada. “Os negócios continuam estagnados, refletindo a ausência de movimentação nos preços. O preço no porto foi de R$ 126,00, Chapecó a R$ 117,00”, comenta.\n\nNo Paraná também não houve muitas alterações no preço. “No porto, Paranaguá vai a R$ 141,00. No interior, em relação à soja da safra 2023/24, a ideia de compra girava em torno de R$ 136,00 por saca CIF Ponta Grossa, com entrega no começo de setembro e pagamento no fim de setembro. No balcão, os preços em Ponta Grossa ficaram em R$ 128,00”, completa.\n\n\n\nPreços parados e negócios apenas pontuais no Mato Grosso do Sul. “O plantio no estado segue atrasado, segundo a CONAB, que não indicou o começo da semeadura no Brasil. O vazio sanitário acabou neste dia 15 para o estado. Dourados R$ 132,00. Campo Grande: R$ 131,00. Maracaju: R$ 131,00. Chapadão do Sul: R$ 129,00. Sidrolândia: R$ 129,00”, indica.\n\nNo Mato Grosso, mais especificamente em Sorriso, os preços subiram para R$ 128 por saca FOB, com retirada em outubro e pagamento em novembro, após estarem a R$ 126 na véspera. “Rodaram volumes pontuais. Preços praticados: Campo Verde: R$ 127,10, Lucas do Rio Verde: R$ 125,60. Nova Mutum: R$ 125,90. Primavera do Leste: R$ 128,00. Rondonópolis: R$ 1330. Sorriso: R$ 125,00”, conclui.",
        "publishedAt": "2024-09-18 23:24:16.257",
        "authorId": 3,
        "categoryId": 3,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/4ef974c1892344c3bc0876ae6e260fe7_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Produção"
    },
    {
        "id": 98,
        "title": "Compras de oportunidade elevam soja em Chicago",
        "subtitle": "A valorização de uma cesta de commodities também influenciou",
        "content": "# Escreva aqui sua notícia",
        "publishedAt": "2024-09-18 23:26:03.844",
        "authorId": 3,
        "categoryId": 3,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/e7646f0bc57a442ab8d1acc6cfb88886_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Internacional"
    },
    {
        "id": 99,
        "title": "Inflação em queda nos EUA e seca no Brasil impulsionam preços do açúcar",
        "subtitle": "O mercado de açúcar iniciou a semana passada de forma cautelosa",
        "content": "O mercado de açúcar iniciou a semana passada de forma cautelosa, com os participantes aguardando o relatório da União da Indústria de Cana-de-Açúcar (UNICA) enquanto a seca severa no Centro-Sul do Brasil continuava a dar suporte aos preços. A análise da Hedgepoint Global Markets destacou que a combinação da seca prolongada e a queda da inflação nos Estados Unidos fortaleceram o mercado de açúcar, elevando os preços do produto.\n\n\n\nLívea Coda, analista de Açúcar e Etanol da Hedgepoint, explicou que, apesar da fraqueza geral no complexo de energia, o açúcar mostrou resiliência, especialmente com as condições climáticas adversas que a principal região produtora do Brasil enfrentou na primeira quinzena de setembro. \"As altas temperaturas e a baixa umidade relativa do ar aumentaram o risco de incêndios nos [canaviais](https://www.agrolink.com.br/culturas/cana-de-acucar/?utm_source=agrolink-detalhe-noticia\\&utm_medium=detalhe-noticia\\&utm_campaign=links-internos)\", acrescentou.\n\nO relatório da UNICA revelou um mix de açúcar de 48,85%, abaixo das expectativas de mercado, que previa um índice acima de 49%. Esse resultado surpreendeu os analistas, reforçando ainda mais o movimento de alta no mercado.\n\nNo campo legislativo, a aprovação do projeto de lei \"Combustíveis do Futuro\" pelo Senado brasileiro trouxe perspectivas de aumento na demanda por biocombustíveis, como o etanol. Entre as principais disposições, o aumento da mistura de biogás no gás natural e as metas para biocombustíveis até 2031 foram destacados. \"Se o mandato de mistura de etanol na gasolina for fixado em 30% para 2025, a demanda por etanol anidro terá um crescimento significativo, gerando oportunidades no setor de biocombustíveis\", afirmou Coda.\n\n\n\nEntretanto, a Hedgepoint destacou que o mercado de açúcar permanece atento à paridade das exportações indianas, com a participação do país no comércio internacional sendo restrita a preços acima de 20-21 c/lb. No mercado de açúcar branco, a entrega de outubro foi robusta, com 544,6 mil toneladas sendo entregues, a segunda maior já registrada em Londres.\n\nEmbora o cenário seja positivo para os preços do açúcar, os biocombustíveis ainda têm um longo caminho a percorrer antes de impactarem diretamente esse mercado. Até lá, o mix de fatores climáticos e macroeconômicos deverá continuar a definir o rumo dos preços, especialmente à medida que a seca no Centro-Sul brasileiro persiste.",
        "publishedAt": "2024-09-18 23:30:22.309",
        "authorId": 3,
        "categoryId": 7,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/1c06c98d2c724a269450333e388ebd11_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "EUA"
    },
    {
        "id": 100,
        "title": "Queimadas afetam colheita de cana e pressionam setor",
        "subtitle": "Incêndios impactam lavouras de cana",
        "content": "Segundo informações divulgadas pela UNICA, a segunda quinzena de agosto trouxe uma leve redução na moagem de cana-de-açúcar no Centro-Sul do Brasil. As unidades produtoras processaram 45,07 milhões de toneladas, registrando uma queda de 3,25% em comparação ao mesmo período da safra 2023/2024. No entanto, o acumulado da safra 2024/2025 até o início de setembro apresenta crescimento, com 422,61 milhões de toneladas moídas, 3,93% a mais que na safra anterior.\n\n\n\nAtualmente, 258 unidades estão em operação no Centro-Sul, sendo 239 focadas no processamento de cana-de-açúcar, nove dedicadas à produção de etanol de milho e dez usinas flex. Em relação à qualidade da matéria-prima, o nível de Açúcares Totais Recuperáveis (ATR) alcançou 155,34 kg por tonelada na segunda quinzena de agosto, um aumento de 0,92% em relação à safra anterior.\n\nA produção de açúcar, no entanto, registrou queda. Foram produzidas 3,26 milhões de toneladas de açúcar, uma redução de 6,02% em relação ao mesmo período da safra passada. Já o etanol apresentou desempenho mais robusto, com um total de 2,45 bilhões de litros produzidos na segunda metade de agosto, sendo 1,56 bilhão de litros de etanol hidratado, representando um crescimento de 10,27%.\n\n\n\nApesar desses números, a UNICA alerta para os efeitos das queimadas, especialmente em São Paulo. Segundo a entidade, incêndios afetaram mais de 231 mil hectares de cana-de-açúcar na segunda quinzena de agosto, o que pode impactar tanto a qualidade da matéria-prima quanto o cronograma de colheita.\n\nNas vendas de etanol, agosto registrou alta de 3,76%, com destaque para o etanol hidratado, que aumentou 6,81% no período.",
        "publishedAt": "2024-09-18 23:30:59.264",
        "authorId": 3,
        "categoryId": 7,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/e4ee32da53ef4717808b32ed01bb2de9_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Brasil"
    },
    {
        "id": 101,
        "title": "São Paulo: calor no fim de agosto aumenta risco de incêndios no campo",
        "subtitle": "Queimadas provocaram prejuízos de mais de R$ 1 bilhão ao agro de SP",
        "content": "A previsão de aumento das temperaturas e de tempo seco no fim de semana eleva o alerta para o alto risco de incêndios nas lavouras do Estado de São Paulo. Nos últimos dias, uma frente fria que atingiu a Região Sudeste ajudou no combate aos focos de incêndio, mas o cenário deve mudar nos próximos dias, trazendo novos desafios para o setor agropecuário, conforme os dados da Secretaria de Agricultura e Abastecimento de São Paulo (SAA).\n\n\n\nDe acordo com dados da SSA, as queimadas registradas no último fim de semana impactaram fortemente as atividades agrícolas, especialmente a pecuária, cana-de-açúcar, fruticultura, heveicultura e apicultura. Os danos causados pelo fogo nas lavouras, pastagens e até a morte de animais já geraram prejuízos superiores a R$ 1 bilhão.\n\nGabriel Rodrigues, meteorologista do Agrolink destacou que a expectativa de que o tempo seco persista até pelo menos 12 de setembro. \"O final de agosto ainda é marcado pela estação seca no estado de São Paulo, que tem início na segunda metade de maio, e historicamente, a estação chuvosa começa a partir da segunda quinzena de setembro. O cenário nas projeções de médio prazo ainda indicam uma condição de tempo seco no estado paulista até pelo menos o dia 12 de setembro. De certa forma, esta previsão está de acordo com os registros históricos\", explica o especialista. \n\n[Veja mais informações sobre o clima em Agrotempo](https://www.agrolink.com.br/agrotempo?utm_source=agrolink-detalhe-noticia\\&utm_medium=detalhe-noticia\\&utm_campaign=links-internos)\n\nAs chuvas ficaram abaixo da média em São Paulo refletindo um inverno ainda mais seco. \"No entanto, vale ressaltar que nos últimos 120 dias, as chuvas ficaram abaixo da média no estado, indicando um inverno ainda mais seco. Além disso, a influência de vários episódios de bloqueios atmosféricos ao longo desta estação, contribuíram com a intensificação do calor e o impedimento do avanço das frentes frias sobre o estado. Condição que estamos vendo, agora no final do mês de agosto, mesmo após a chegada de uma massa de ar mais frio, continua Rodrigues. \n\n\n\nCom o aumento das temperaturas previsto para os últimos dias de agosto, a Defesa Civil do Estado de São Paulo emitiu um alerta para o alto risco de queimadas nas regiões produtivas. Para evitar novos focos de incêndio, é fundamental que a população colabore, adotando medidas como evitar queimar lixo, não acender fogueiras, não soltar balões (prática considerada crime ambiental), e manter aceiros limpos em volta das propriedades.\n\n\"A presença de um bloqueio atmosférico, que atuará nas próximas semanas. Esse bloqueio, além de impedir a formação das nuvens carregadas e o avanço das chuvas das frentes frias, contribui com a redução dos índices de umidade, favorecendo então um ambiente altamente propício para o alastramento dos incêndios e queimadas no estado. Contudo, as projeções de longo prazo, estão mostrando um cenário mais úmido entre a última semana de setembro e primeira semana de outubro. Condição que pode aliviar, momentaneamente, as condições secas no estado de São Paulo\" finaliza o meteorologista.\n\nPara mitigar esses prejuízos, a SAA destinou R$ 110 milhões aos produtores rurais paulistas afetados pelas queimadas, por meio do Fundo de Expansão do Agronegócio Paulista (FEAP). Os produtores interessados em acessar esse crédito devem procurar a Casa da Agricultura de seus municípios, conforme as informações da Secretaria de Agricultura e São Paulo.\n\n\n\nConforme o informado pela Secretaria de Agricultura e Abastecimento de São Paulo, em caso de emergência, a Defesa Civil (199) e o Corpo de Bombeiros (193) estão disponíveis para atendimento. As regiões sob alerta incluem Andradina, Araçatuba, Assis, Barretos, Bauru, Campinas, Campos do Jordão, Franca, Guaratinguetá, Iperó, Itapeva, Jales, Jaú, Jundiaí, Marília, Ourinhos, Presidente Prudente, Ribeirão Preto, São Carlos, São José do Rio Preto, Sorocaba e Votuporanga.",
        "publishedAt": "2024-09-18 23:32:10.795",
        "authorId": 3,
        "categoryId": 7,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/3cd974ea0a724522b78b6c5d17adb406_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Produção"
    },
    {
        "id": 102,
        "title": "Preços do frango vivo sobem em setembro",
        "subtitle": "Exportações de carne de frango caem consideravelmente",
        "content": "Segundo a análise da edição de setembro do Boletim Agropecuário produzido pela Empresa de Pesquisa Agropecuária e Extensão Rural de Santa Catarina (Epagri) divulgado pelo Observatório Agro Catarinense, nas duas primeiras semanas de setembro, os preços do frango vivo apresentaram leve alta nos dois principais estados produtores. No Paraná, houve um aumento de 0,5% em comparação com o mês anterior, enquanto em Santa Catarina o crescimento foi de 0,4%. Quando comparados aos preços de setembro do ano passado, as altas foram de 4,5% no Paraná e 2,9% em Santa Catarina, considerando os valores nominais.\n\n\n\nEm relação às variações regionais, os preços nas duas primeiras semanas de setembro mantiveram-se estáveis nas regiões Meio Oeste e Litoral Sul. No entanto, a região Oeste registrou uma alta de 1,2% no período. Comparado a setembro de 2023, o Meio Oeste viu um aumento de 3,1%, e o Litoral Sul, de 0,7%, enquanto o Oeste sofreu uma queda de 6,6%, todos os valores corrigidos pelo IGP-DI.\n\nNo mercado atacadista, os preços da carne de frango mostraram variações distintas no início de setembro. O peito com osso e o filé de peito apresentaram altas de 1,7% e 0,8%, respectivamente. Por outro lado, a coxa/sobrecoxa e o frango inteiro congelado tiveram variações negativas de -0,8% e -0,1%. A variação média dos quatro cortes foi de 0,4%, com um aumento acumulado de 18,6% no ano, conforme dados do Boletim Agropecuária.\n\nQuando comparados aos preços de setembro de 2023, os valores atuais apresentam aumentos em todos os cortes: 34,2% para o filé de peito, 30,8% para o peito com osso, 10,3% para o frango inteiro e 3,9% para a coxa/sobrecoxa. A variação média dos quatro cortes foi de 19,8%.\n\n\n\nDe acordo com a Embrapa Suínos e Aves, o custo de produção de frangos em aviário climatizado positivo em Santa Catarina foi de R$ 4,85/kg em agosto, refletindo uma alta de 2,1% em relação ao mês anterior e 4,0% acima do custo de agosto de 2023, corrigido pelo IGP-DI. No acumulado do ano, o aumento é de 5,2%. A relação de troca insumo-produto caiu levemente nas duas primeiras semanas de setembro, com uma redução de 0,5% devido ao aumento no preço do frango vivo na região Oeste, parcialmente compensado pela alta no preço do [milho](https://www.agrolink.com.br/culturas/milho?utm_source=agrolink-detalhe-noticia\\&utm_medium=detalhe-noticia\\&utm_campaign=links-internos).\n\nNo setor de exportações, o Brasil enviou 318,5 mil toneladas de carne de frango em agosto, o que representa uma queda de 29,6% em relação ao mês anterior e de 24,4% na comparação com agosto de 2023. As receitas caíram para US$ 609,0 milhões, uma redução de 30,3% em relação ao mês anterior e de 25,2% na comparação anual. A Associação Brasileira de Proteína Animal (ABPA) atribui essa queda ao surto de doença de Newcastle no Rio Grande do Sul, que afetou especialmente os embarques para a China e o México.\n\nNo acumulado de janeiro a agosto, o Brasil exportou 3,30 milhões de toneladas de carne de frango, gerando receitas de US$ 6,04 bilhões, o que representa uma queda de 3,2% em quantidade e 10,2% em valor em comparação com o mesmo período do ano passado. Santa Catarina exportou 69,9 mil toneladas em agosto, com uma queda de 32,3% em relação ao mês anterior e de 28,8% na comparação anual. As receitas foram de US$ 141,0 milhões, com uma redução de 31,5% em relação ao mês anterior e de 31,9% na comparação anual.\n\n\n\nApesar das quedas recentes, o valor médio da carne de frango in natura exportada por Santa Catarina foi de US$ 1.934,82 por tonelada em agosto, uma pequena queda de 0,1% em relação ao mês anterior, mas 3,8% abaixo do valor de agosto de 2023. No acumulado do ano, o estado exportou 736,4 mil toneladas, com receitas de US$ 1,42 bilhão, apresentando um aumento de 0,5% em quantidade, mas uma queda de 10,5% em valor, comparado ao mesmo período do ano anterior. Santa Catarina foi responsável por 23,5% das receitas geradas pelas exportações brasileiras de carne de frango nos primeiros oito meses de 2024.",
        "publishedAt": "2024-09-18 23:34:00.230",
        "authorId": 3,
        "categoryId": 13,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/f0d1448d1c614b63a00ed60510e4fdf6_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado"
    },
    {
        "id": 103,
        "title": "Exportações de ovos caem pelo segundo mês consecutivo",
        "subtitle": "Brasil exportou 1,239 mil toneladas de ovos in natura e processados no último mês",
        "content": "As exportações de ovos comerciais do Brasil registraram nova queda em agosto, consolidando o segundo mês consecutivo de recuo. Esse desempenho negativo foi impulsionado, sobretudo, pela redução nos embarques de produtos processados, como ovalbumina e ovos secos ou cozidos, setores que apresentaram baixa expressiva.\n\n\n\nSegundo dados informados pelo Cepea, com base nas estatísticas da Secex, o Brasil exportou 1,239 mil toneladas de ovos in natura e processados no último mês, o que representa uma queda de 4,7% em relação a julho e uma redução significativa de 42% em comparação a agosto de 2023. Destas exportações, apenas 24,6% (equivalente a 305 toneladas) foram de produtos processados, o menor índice registrado desde dezembro de 2022.",
        "publishedAt": "2024-09-18 23:34:30.741",
        "authorId": 3,
        "categoryId": 13,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/2e67af479dc24df9ae6983f5fc124bc2_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Exportação"
    },
    {
        "id": 104,
        "title": "Preços da carne de frango recuperam em agosto após queda",
        "subtitle": "O aumento dos preços é impulsionado pela demanda aquecida",
        "content": "De acordo com informações divulgadas pelo Centro de Estudos Avançados em Economia Aplicada (Cepea), os preços médios da carne de frango, que enfrentaram queda em julho, apresentaram sinais de recuperação ao final de agosto. O aumento dos preços é impulsionado pela demanda aquecida, especialmente na primeira quinzena do mês, coincidente com o pagamento de salários, e pela oferta interna mais restrita.\n\n\n\nO mercado de frango vivo também experimentou um aumento nos preços devido à combinação de demanda elevada pela carne e oferta reduzida do animal. No entanto, enquanto o mercado interno mostra sinais de recuperação, as exportações brasileiras de carne de frango in natura continuam enfraquecidas.",
        "publishedAt": "2024-09-18 23:35:02.027",
        "authorId": 3,
        "categoryId": 13,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/827426b4de864e86b90671cdce04eaa1_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado"
    },
    {
        "id": 105,
        "title": "Captação do leite cai 6,16% no Brasil",
        "subtitle": "Queda na captação de leite no Sul e Centro-Oeste impacta produção nacional",
        "content": "A captação de leite no Brasil registrou uma queda de 6,16% no segundo trimestre de 2024 em relação ao trimestre anterior, de acordo com a análise semanal do Instituto Mato-grossense de Economia Agropecuária (Imea) e dados do IBGE. O volume total captado no período somou 5,83 bilhões de litros. A principal responsável por essa redução foi a região Sul, que sofreu uma retração de 5,30%, sendo puxada principalmente pelo Rio Grande do Sul, onde as enchentes resultaram em uma queda de 10,08% no volume captado em relação ao primeiro trimestre de 2024.\n\n\n\nSegundo a análise, na região Centro-Oeste, a entrada do período seco também impactou a produção, com uma queda de 10,77%, resultando em um total de 0,62 bilhão de litros captados. Mato Grosso do Sul e Mato Grosso lideraram as retrações, com reduções de 23,21% e 18,43%, respectivamente.\n\n\n\nPara o terceiro trimestre de 2024, a continuidade do período seco na região Centro-Oeste pode continuar a limitar a captação de leite, enquanto as pastagens de inverno na região Sul devem proporcionar uma recuperação, sustentando um leve aumento na captação a nível nacional, conforme os dados do Imea.",
        "publishedAt": "2024-09-18 23:36:03.394",
        "authorId": 3,
        "categoryId": 12,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/8c91bc5aca8344c4841291e37d8435fa_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Produção"
    },
    {
        "id": 92,
        "title": "Café robusta atinge recordes históricos e supera R$ 1.500 por saca",
        "subtitle": "Valorização é de 100%",
        "content": "Os preços do café robusta no Brasil continuam a atingir novos recordes, com a saca de 60 kg fechando acima de R$ 1.500,00 pela primeira vez desde o final da semana passada. O movimento de alta nas cotações, que já era observado desde o último trimestre de 2023, representa uma valorização de 100% em comparação ao preço de R$ 740/sc registrado no período.\n\n\n\nSegundo informações do Cepea (Centro de Estudos Avançados em Economia Aplicada), o aumento expressivo nos preços do robusta é atribuído a uma série de fatores. O clima adverso prejudicou a safra brasileira e deve impactar também a produção do Vietnã, maior produtor mundial da variedade. Além disso, dificuldades no fluxo global de mercadorias, que elevaram os custos de frete, têm atrapalhado os envios da Ásia para a Europa.\n\n\n\nO clima seco e quente nas principais regiões produtoras também gera preocupações quanto à safra brasileira de 2025/26, tanto para o robusta quanto para o arábica.",
        "publishedAt": "2024-09-18 22:03:12.732",
        "authorId": 3,
        "categoryId": 6,
        "imageUrl": "https://www.agrolink.com.br/upload/imagens-resizes/2d0457adbba34d0eb7314f3850c7f3ae_858x483.jpg",
        "status": "Publicado",
        "thumbnailText": "Mercado"
    },
];